export const GET_ALL_BLOGS_REQUEST = "GET_ALL_BLOGS_REQUEST";
export const GET_ALL_BLOGS_SUCCESS = "GET_ALL_BLOGS_SUCCESS";
export const GET_ALL_BLOGS_FAILURE = "GET_ALL_BLOGS_FAILURE";

export const GET_BLOG_BY_ID_REQUEST = "GET_BLOG_BY_ID_REQUEST";
export const GET_BLOG_BY_ID_SUCCESS = "GET_BLOG_BY_ID_SUCCESS";
export const GET_BLOG_BY_ID_FAILURE = "GET_BLOG_BY_ID_FAILURE";

export const USER_ALL_BLOGS_REQUEST = "USER_ALL_BLOGS_REQUEST";
export const USER_ALL_BLOGS_SUCCESS = "USER_ALL_BLOGS_SUCCESS";
export const USER_ALL_BLOGS_FAILURE = "USER_ALL_BLOGS_FAILURE";
